http:
  port: "8088"

db:
  host: "mudb.learn.mulesoft.com"
  port: "3306"
  user: "mule"
  password: "mule"
  database: "training"
delta:
  location: "http://mu.learn.mulesoft.com/delta?wsdl"
  service: "TicketServiceService"
  port: "TicketServicePort"
  address: "http://mu.learn.mulesoft.com/delta"
HTTP_Request:
  host: "mu.learn.mulesoft.com"
  port: "80"
sfdc:
  username: "besufikad@thiotec.com"
  password: "Serki&l18"
  token: "tD0TxnnBRiN2vSNGxSaX34Q8"